Microsoft.Toolkit.Graph/Providers/MockProvider.cs

Resolves #24 for now
Works around issue with how Graph SDK resolves urls, detailed here: https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/59
For now, we know if we have a complex Query String that we should swap the first '&' with a '?' to make it a valid proxy service url.

Add hack for MockProvider to workaround SDK issue

---

Microsoft.Toolkit.Graph.Controls/Controls/LoginButton/LoginButton.Properties.cs
Microsoft.Toolkit.Graph.Controls/Controls/LoginButton/LoginButton.cs

Fixes #14
- Bugfix
The login button is not disabled during login/logout operations.
The login button will now be disabled during login/logout. I'm reusing the `IsLoading` property to enable/disable the button. It will be set to true before starting the operations.
The login/logout operations will be disabled while `IsLoading` is true.

Disable login button while login or logout

---

Microsoft.Toolkit.Graph.Controls/Controls/LoginButton/LoginButton.cs

- Bugfix
When clicking on the sign out hyperlink in the authenticated user flyout, the flyout remains visible without any information until the sign out is complete:
During this phase, the hyperlink remains clickable but is not doing anything.
The authenticated user flyout will now be dismissed immediately when clicking on the sign out hyperlink.

Hide sign out flyout on click

---

Directory.Build.props
Microsoft.Toolkit.Graph.Controls/Controls/GraphPresenter/GraphPresenter.cs
Microsoft.Toolkit.Graph.Controls/Microsoft.Toolkit.Graph.Controls.csproj
Microsoft.Toolkit.Graph.Controls/Providers/InteractiveProviderBehavior.cs
Microsoft.Toolkit.Graph/Microsoft.Toolkit.Graph.csproj
Samples/XAML Islands/UWP-XamlApplication/UWP-XamlApplication.csproj
Samples/XAML Islands/WPF-Core-GraphApp/WPF-Core-GraphApp.csproj
build/build.cake
global.json
version.json

Updated Main toolkit dependency to 7.0.0-preview2, updated dependencies in general, and now using the DispatcherQueue.
Fixes #57
- Bugfix 
- Feature 
- Build or CI related changes 

Update to 7.0.0-preview2.

---

Directory.Build.props
Microsoft.Toolkit.Graph.Controls/Controls/GraphPresenter/GraphPresenter.cs
Microsoft.Toolkit.Graph.Controls/Controls/LoginButton/LoginButton.xaml
Microsoft.Toolkit.Graph.Controls/Controls/PeoplePicker/PeoplePicker.xaml
Microsoft.Toolkit.Graph.Controls/Controls/PersonView/PersonView.xaml
Microsoft.Toolkit.Graph.Controls/Microsoft.Toolkit.Graph.Controls.csproj
Microsoft.Toolkit.Graph/Microsoft.Toolkit.Graph.csproj
Microsoft.Toolkit.Graph/Providers/ProviderManager.cs
SampleTest/App.xaml
SampleTest/MainPage.xaml
SampleTest/SampleTest.csproj
Samples/XAML Islands/UWP-XamlApplication/App.xaml
Samples/XAML Islands/UWP-XamlApplication/SamplePage.xaml
Samples/XAML Islands/UWP-XamlApplication/UWP-XamlApplication.csproj
Samples/XAML Islands/WPF-Core-GraphApp/MainWindow.xaml
Samples/XAML Islands/WPF-Packaged-App/WPF-Packaged-App.wapproj

@azchohfi want to take a quick look?
Updated our NuGets, tested both the UWP and XAML Islands samples locally.
Also applied XAML Styler, so can ignore the XAML Formatting. Tested and removed the workaround for https://github.com/microsoft/microsoft-ui-xaml/issues/1286

Update to 7.0.0-preview4

---

CommunityToolkit.Net.Graph/CommunityToolkit.Net.Graph.csproj
CommunityToolkit.Net.Graph/Extensions/GraphExtensions.People.cs
CommunityToolkit.Net.Graph/Extensions/GraphExtensions.Users.cs
CommunityToolkit.Net.Graph/Extensions/GraphExtensions.cs
CommunityToolkit.Net.Graph/Extensions/ProviderExtensions.cs
CommunityToolkit.Uwp.Graph.Controls/CommunityToolkit.Uwp.Graph.Controls.csproj
CommunityToolkit.Uwp.Graph.Controls/Controls/GraphPresenter/GraphPresenter.cs
CommunityToolkit.Uwp.Graph.Controls/Controls/LoginButton/LoginButton.cs
CommunityToolkit.Uwp.Graph.Controls/Controls/PersonView/PersonView.cs
CommunityToolkit.Uwp.Graph.Controls/Controls/PersonView/PersonView.xaml

Fixes #52
- Feature
Currently, the Graph based projects use the Beta Graph SDK all the time. There is no V1 usage at the moment.
We need to use V1 for production/stability purposes, but sometimes we also need to make beta api calls (e.g. user photo). This is not possible currently.
First off I've removed all references to the Beta Graph SDK, and added the v1 `Microsoft.Graph` nuget package instead.
I then organized the methods in the GraphExtensions to be split on the API type:
- GraphExtensions.cs
- GraphExtensions.People.cs
- GraphExtensions.Users.cs
Lastly, I added a new extension method to the ProviderExtensions, `IProvider.BetaGraph()`. Calling BetaGraph will return a GraphServiceClient that is otherwise identical to the other, but with the …

Updating references to use Graph V1 and introducing BetaGraph extension

---

CommunityToolkit.Uwp.Graph.Controls/Helpers/RoamingSettings/BaseRoamingSettingsDataStore.cs
CommunityToolkit.Uwp.Graph.Controls/Helpers/RoamingSettings/OneDriveDataSource.cs
CommunityToolkit.Uwp.Graph.Controls/Helpers/RoamingSettings/OneDriveDataStore.cs

…so serialization/deserialization is more consistent

Updates to baseRoamingSettingsDataStore 

---

CommunityToolkit.Uwp.Graph.Controls/CommunityToolkit.Uwp.Graph.Controls.csproj
CommunityToolkit.Uwp.Graph.Controls/Helpers/RoamingSettings/BaseRoamingSettingsDataStore.cs
CommunityToolkit.Uwp.Graph.Controls/Helpers/RoamingSettings/OneDriveDataStore.cs
CommunityToolkit.Uwp.Graph.Controls/Helpers/RoamingSettings/UserExtensionDataStore.cs
UnitTests/UnitTests.UWP/RoamingSettings/Test_OneDriveDataStore.cs
UnitTests/UnitTests.UWP/RoamingSettings/Test_UserExtensionDataStore.cs

Ensures the Cache is initialized to an empty dictionary instead of null.

Update Cache to default to empty Dictionary

---

CommunityToolkit.Authentication.Uwp/AccountsSettingsPaneConfig.cs
CommunityToolkit.Authentication.Uwp/WebAccountCommandParameter.cs
CommunityToolkit.Authentication.Uwp/WindowsProvider.cs
Samples/UwpWindowsProviderSample/AccountManagerButton.xaml
Samples/UwpWindowsProviderSample/AccountManagerButton.xaml.cs
Samples/UwpWindowsProviderSample/App.xaml.cs
Samples/UwpWindowsProviderSample/MainPage.xaml
Samples/UwpWindowsProviderSample/MainPage.xaml.cs
Samples/UwpWindowsProviderSample/UwpWindowsProviderSample.csproj

**Feature**
Support display account management panel:
At this stage, `WindowsProvider` provides login and logout functions, the logout process does not require user involvement.
Some usage scenarios may need to display the currently logged-in user and provide some custom operations.
**Breaking changes**
The login panel and the management panel are two different usage scenarios, and their `HeaderText` may not be mixed, so I made some modifications:
1. Modify the original `HeaderText` to `AddAccountHeaderText`.
2. Add a new property `ManageAccountHeaderText` is used to display in the account management panel.
3. The constructor parameters of `AccountsSettingsPaneConfig` have been …

Support display account management panel

---

CommunityToolkit.Authentication.Msal/MsalProvider.cs
CommunityToolkit.Authentication.Uwp/WindowsProvider.cs
CommunityToolkit.Authentication/BaseProvider.cs
CommunityToolkit.Authentication/IProvider.cs
CommunityToolkit.Authentication/MockProvider.cs

Fixes #
- Feature 
This PR introduces a new property on IProvider called `CurrentAccountId`, which reflects the identifier of the currently signed in user account. 
- For `MsalProvider` the id comes from `Microsoft.Identity.Client.AccountId.Identifier`
- For `WindowsProvider` the id comes from `Windows.Security.Credentials.WebAccount.Id`
- For `MockProvider` the id is a dummy value, "mock-account-id".
When NOT signed in `CurrentAccountId` returns `null`.

Added CurrentAccountId to IProvider

---

CommunityToolkit.Graph.Uwp/CommunityToolkit.Graph.Uwp.csproj
CommunityToolkit.Graph.Uwp/Triggers/ProviderStateTrigger.cs
SampleTest/MainPage.xaml

Fixes #97 #9 
- Feature
Introducing a new XAML trigger, `CommunityToolkit.Graph.Uwp.ProviderStateTrigger`.
This trigger will allow developers to trigger VisualStates in XAML in response to any authentication state changes on the global provider. 
Use the `ProviderStateTrigger.ActiveState` property to respond to changes in the global authentication provider. 
The `ActiveState` property supports all ProviderStates values (`Loading`, `SignedOut`, `SignedIn`).
Example:
```csharp
<VisualStateManager.VisualStateGroups xmlns:uwp="using:CommunityToolkit.Graph.Uwp">
<VisualStateGroup>
<VisualState>
<VisualState.StateTriggers>
<uwp:ProviderStateTrigger ActiveState="SignedIn" />
</VisualState.StateTriggers>
<VisualState.Setters>
<Setter …
```

New ProviderStateTrigger

---

CommunityToolkit.Authentication.Msal/MsalProvider.cs
CommunityToolkit.Authentication.Uwp/WindowsProvider.cs
CommunityToolkit.Authentication/BaseProvider.cs
CommunityToolkit.Authentication/IProvider.cs
CommunityToolkit.Authentication/MockProvider.cs

Fixes #111
- Feature 
Currently, there is no way to request an access token for scopes that were not initially requested during provider construction.
This limits the ability to adopt Graph APIs over time, as features are introduced.
```
// In app startup code:
// The provider is constructed with an initial set of scopes.
string[] initialScopes = new string[] { "User.Read" };
ProviderManager.Instance.GlobalProvider = new WindowsProvider(initialScopes);
// Somewhere else in the app:
// GetTokenAsync can only retrieve a token configured for the scopes created during provider construction.
IProvider provider = ProviderManager.Instance.GlobalProvider;
string token = await provider.GetTokenAsync(silentOnly: false);
```
The new behavior adds an …

Added scopes parameter to IProvider.GetTokenAsync

---

CommunityToolkit.Authentication.Uwp/CommunityToolkit.Authentication.Uwp.csproj
CommunityToolkit.Graph.Uwp/CommunityToolkit.Graph.Uwp.csproj
CommunityToolkit.Graph.Uwp/Controls/LoginButton/LoginButton.Properties.cs
CommunityToolkit.Graph.Uwp/Controls/LoginButton/LoginButton.cs
CommunityToolkit.Graph.Uwp/Controls/LoginButton/LoginButton.xaml
Samples/ManualGraphRequestSample/MainPage.xaml
UnitTests/UnitTests.UWP/RoamingSettings/Test_OneDriveDataStore.cs
UnitTests/UnitTests.UWP/RoamingSettings/Test_UserExtensionDataStore.cs

Also updated some broken tests after provider event name change, and a bug in the LoginButton.
- Bugfix
WCT uses a special csproj format for UWP projects, and the Graph-Controls repo should match.
Here is an example from WCT:
https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/main/Microsoft.Toolkit.Uwp.UI.Controls.Input/Microsoft.Toolkit.Uwp.UI.Controls.Input.csproj
The csproj formats in the following packages now match the way WCT handles UWP projects:
1. `CommunityToolkit.Authentication.Uwp`
2. `CommunityToolkit.Graph.Uwp`

 Adjusted uwp project files to match WCT.

---

CommunityToolkit.Authentication/ProviderManager.cs

Fixes #
- Feature
SwitchPresenter from WCT doesn't work well with the GlobalProvider state as it exists today. It is not possible to simply use `ProviderManager.Instance.GlobalProvider.State` because the `GlobalProvider.State` is only available after the provider has been set, so the initial binding fails and updates are never processed.
Use the new `GlobalProviderState` getter to retrieve the current state of the active GlobalProvider, or `null` if none.
This is helpful for binding in XAML, since `GlobalProviderState` is consistently available via the ProviderManager.Instance singleton.
```
<controls:SwitchPresenter Value="{x:Bind auth:ProviderManager.Instance.GlobalProviderState, Mode=OneWay}">
<controls:Case Value="{x:Bind …
```

Added GlobalProviderState to ProviderManager property for easy binding

---

CommunityToolkit.Authentication.Uwp/AccountsSettingsPaneConfig.cs
CommunityToolkit.Authentication.Uwp/WebAccountProviderType.cs
CommunityToolkit.Authentication.Uwp/WindowsProvider.cs
Samples/UwpWindowsProviderSample/App.xaml.cs

Fixes #116
- Feature
Currently WindowsProvider *only* supports authentication of consumer MSA accounts.
This PR introduces new authentication support for organizational AAD accounts. 
The `WebAccountProviderType` enum has a new `Aad` value that can be used to specify that only organizational accounts should be available to the user. Configuration in AAD is required to support authentication of organizational accounts.
I have also added a new `WebAccountProviderType.Local` option which uses whatever the active local account is. When using `Local`, configuration in AAD and a Store app association is required for the app to work consistently. If only MSA/AAD is meant to be supported, the appropriate `WebAccountProviderType.Msa/Aad` should be …

Integrated AAD support

---

CommunityToolkit.Authentication.Msal/MsalProvider.cs
CommunityToolkit.Authentication.Uwp/WindowsProvider.cs
CommunityToolkit.Authentication/BaseProvider.cs
CommunityToolkit.Authentication/IProvider.cs
CommunityToolkit.Authentication/MockProvider.cs

Fixes #
- Bugfix
WAM doesn't support incremental consent, so this function is deceiving. Only pre-authorized scopes will return a token successfully, in which case they should be included with the rest of the scopes provided during provider construction.
I've removed the *scopes* param from IProvider.GetTokenAsync.

Removed scopes param from IProvider.GetTokenAsync

---

CommunityToolkit.Graph.Uwp/Controls/LoginButton/LoginButton.Properties.cs
CommunityToolkit.Graph.Uwp/Controls/LoginButton/LoginButton.cs
CommunityToolkit.Graph.Uwp/Controls/LoginButton/LoginButton.xaml

Fixes #101
- Feature
Currently, the Login/Logout-Completed events on LoginButton only fire when actually interacting with the button. This can make it difficult to use the LoginButton events reliably, since they won't fire if the GlobalProvider is updated directly.
The new behavior allows the LoginButton to emit Login/Logout-Completed events in response to state changes in the GlobalProvider. When the GlobalProvider state changes, the LoginButton will emit those events as appropriate. 
Note: The Login/Logout-Initiated events will not fire. This is because we have limited ability to understand the login flow based on the ProviderState enum values, SignedIn, SignedOut, and Loading.

Updated LoginButton events to respond to GlobalProvider

---

.github/PULL_REQUEST_TEMPLATE.md
Directory.Build.props
README.md
nuget.config

Build is failing due to org rename.
- Bugfix
- Build or CI related changes
Broken build.
The Build builds 🐱‍💻

Org rename: windows-toolkit -> CommunityToolkit

---

CommunityToolkit.Authentication/ProviderManager.cs

Fixes race condition issue with OnProviderStateChanged event.

---

CommunityToolkit.Authentication/ProviderManager.cs

Fixes #
- Bugfix
This is a one word change:
```
// OLD
private void OnProviderStateChanged(object sender, ProviderStateChangedEventArgs args)
{
ProviderStateChanged?.Invoke(sender, args); // <- 'sender' is wrong
PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(State)));
}
// NEW
private void OnProviderStateChanged(object sender, ProviderStateChangedEventArgs args)
{
ProviderStateChanged?.Invoke(this, args); <- Need to use 'this' instead
PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(State)));
}
```
This is inspired by a recent bugfix in main.

Updated OnProviderStateChanged method

---

CommunityToolkit.Graph.Uwp/Controls/LoginButton/LoginButton.cs
CommunityToolkit.Graph.Uwp/Controls/PeoplePicker/PeoplePicker.cs
CommunityToolkit.Graph.Uwp/Controls/PersonView/PersonAvatarType.cs
CommunityToolkit.Graph.Uwp/Controls/PersonView/PersonView.Properties.cs
CommunityToolkit.Graph.Uwp/Controls/PersonView/PersonView.cs
CommunityToolkit.Graph.Uwp/Controls/PersonView/PersonView.xaml
CommunityToolkit.Graph.Uwp/Controls/PersonView/PersonViewType.cs
CommunityToolkit.Graph/Extensions/GraphExtensions.Users.cs
SampleTest/MainPage.xaml
SampleTest/SampleTest.csproj
SampleTest/Samples/PersonView/PersonViewSample.xaml
SampleTest/Samples/PersonView/PersonViewSample.xaml.cs

Fixes #10, #6, #26, #28
- Feature
- Refactoring (no functional changes, no api changes)
The PersonView has a few bugs, and after looking through the code I decided a bit of refactoring would make it easier to read and maintain, as well as naturally fixing some bugs inherent in the previous model.
- `PersonAvatarType` - `Photo` or `Initials`
- `UserPhoto` setter is now internal
- New VisualStates to match `ProviderStates` enum
- New `PersonViewType` enum value, `ThreeLines`
- New `PersonViewSample` page
- Fixed bug #10
- Fixed bug #6
- Fixed bug #26
- Fixed bug #28
- Needs Docs

Major refactor of PersonView with new sample page

---

CommunityToolkit.Authentication.Uwp/WindowsProvider.cs

Fixes #132 
- Bugfix
Currently, UI based calls in the WindowsProvider are not protected in anyway. Causing occasional failures when called from a non-UI thread.
The UI dependant calls in WindowsPRovider are now wrapped with calls to `DispatcherQueue.GetForCurrentThread().TryEnqueue(...);` preventing threading errors regardless of calling location.

Wrapped UI dependant calls in WindowsProvider with dispatchers

---

CommunityToolkit.Authentication.Uwp/WindowsProvider.cs
CommunityToolkit.Graph.Uwp/CommunityToolkit.Graph.Uwp.csproj
CommunityToolkit.Graph.Uwp/Controls/GraphPresenter/GraphPresenter.cs
CommunityToolkit.Graph/CommunityToolkit.Graph.csproj
SampleTest/App.xaml.cs
SampleTest/SampleTest.csproj
Samples/ManualGraphRequestSample/App.xaml.cs
Samples/UwpMsalProviderSample/App.xaml.cs
Samples/UwpWindowsProviderSample/App.xaml.cs
UnitTests/UnitTests.UWP/UnitTests.UWP.csproj

My latest fix for using DispatcherQueue had some late comments, and I also made a mistake and broke the build. This should fix everything up.

Updated dispatcher usage in WindowsProvider and samples.

---

CommunityToolkit.Authentication/MockProvider.cs

Fixes #140
- Bugfix
MockProvider is currently broken because the underlying service endpoint changed.
Instead of pointing to a hardcoded proxy url, we now make a request to a middle service to get the proxy url, and then use that for any outgoing requests.

Updated mock service endpoint in MockProvider

---

CommunityToolkit.Graph.Uwp/Controls/LoginButton/LoginButton.cs
CommunityToolkit.Graph.Uwp/Controls/PeoplePicker/PeoplePicker.cs
CommunityToolkit.Graph.Uwp/Controls/PersonView/PersonView.cs
CommunityToolkit.Graph/Extensions/GraphExtensions.People.cs

- Bugfix
When the `GraphServiceClient` fails to make a request for whatever reason and throws an exception, in most cases we eat the exception and move on. This makes it difficult to understand WHY a request has failed and whether the exception encountered is part of normal logical flow (e.g. 404 - Not Found), or actually unexpected.
In the new behavior, Graph client extension methods no longer eat exceptions, so any `GraphServiceClient` exceptions will bubble up to the caller.
The controls have also been updated to handle any expected exceptions that may occur when using the `GraphServiceClient` to make requests, and rethrow any unexpected ones. This increases stability for controls like `PersonView`, which is frequently used to represent …

Updated how Graph service exceptions are handling in controls

---

CommunityToolkit.Authentication.Msal/CommunityToolkit.Authentication.Msal.csproj
CommunityToolkit.Graph.Uwp/CommunityToolkit.Graph.Uwp.csproj
CommunityToolkit.Graph.Uwp/Controls/GraphPresenter/GraphPresenter.cs
CommunityToolkit.Graph/CommunityToolkit.Graph.csproj
Directory.Build.props
Directory.Build.targets
SampleTest/MainPage.xaml
SampleTest/SampleTest.csproj
UnitTests/UnitTests.UWP/UnitTests.UWP.csproj
Windows-Toolkit-Graph-Controls.sln
build/Windows.Toolkit.Common.props
build/Windows.Toolkit.Common.targets
build/Windows.Toolkit.UWP.Build.targets
build/Windows.Toolkit.Workarounds.Xaml.targets

Fixes #144
- Bugfix
The nuget icon is missing from the published preview packages on Nuget.
I used WCT as a reference to update the property and targets files for the solution and add the icon.
I also noticed that after this change, the GraphPresenter was having a tough time deserializing some types, so I converted it from Newtonsoft Json to System.Text.Json as well to fix up the errors.

Update nuget icon

---

README.md

Update dead link in readme

---

SampleTest/Samples/PeoplePickerSample.xaml
SampleTest/Samples/PeoplePickerSample.xaml.cs

Fixes #149
We re-write the sample to use an external collection as a developer would in their app. This then properly lets the ItemsControl display just the tokenized items. (Though there's still an issue with how TokenizingTextBox behaves we should resolve.)
- Sample app changes
Trying to point to the ItemsSource of the TokenizingTextBox gives us the wrong collection.
We use an external collection (as a developer would bind to their data model) and use that to bind to both the TTB and the ItemsControl. Then it works as intended.
Will open an issue on the main repo for tracking a fix to the underlying TTB.

Fixes #149 - Update Sample to use External ObservableCollection

---

CommunityToolkit.Authentication.Msal/MsalProvider.cs

Fixes #
https://github.com/CommunityToolkit/Graph-Controls/issues/170
- Bugfix
Providing TenantId causes both WithTenantId and WithAuthority to be specified and those are mutually exclusive resulting in error
Providing TenantId excludes WithAuthority

fix(msalprovider): Fix error when providing TenantId

---

CommunityToolkit.Authentication.Msal/MsalProvider.cs
CommunityToolkit.Authentication.Uwp/WindowsProvider.cs
CommunityToolkit.Authentication/BaseProvider.cs
CommunityToolkit.Authentication/IProvider.cs
CommunityToolkit.Authentication/MockProvider.cs

Fixes #
Feature
GetTokenAsync always requests token with scopes set in class construction.
Optional parameter for GetTokenAsync to supply scopes specific to token request.
Change was already included in documentation, must have been lost along the way.

Add optional Scopes parameter to BaseProvider

---

settings.xamlstyler

I was comparing your settings.xamlstyler with mine to see the difference and noticed a few typos (I've been using this file for about a month and copied the settings from here https://github.com/Xavalon/XamlStyler/wiki/External-Configurations).
I originally noticed this issue in
WindowsCommunityToolkit and thought it might be a CopyPaste issue
Fixes #
- Refactoring (no functional changes, no api changes)

Fixed typos in settings.xamlstyler

---

CommunityToolkit.Authentication.Uwp/WindowsProvider.cs

Fixes #190 
- Bugfix
When adding a `WebAccountProvider`, there is no **null** judgment on the acquired provider, resulting in a null reference in the provider added to the list, which directly causes an unexpected provider (null) to be passed in when the `WebAccountProviderCommand` is created, causing the process to be interrupted and unable to log in.
Create a new method and add it to the list only when the obtained `WebAccountProvider` is not null.

Avoid adding empty providers

---

CommunityToolkit.Authentication.Uwp/WindowsProvider.cs

Fixes #192 
- Bugfix
Failed when trying to grant AAD multiple permissions
Grant AAD account multiple permissions normally

Change WindowsProvider permission scope separator to space
